version: "3.9"
services:
    mssql_db:
        image: "mcr.microsoft.com/mssql/server:${MSSQL_IMAGE_VERSION:-latest}"
        ports:
        - "1433:1433"
        environment:
            SA_PASSWORD: ${SA_PASSWORD}
            ACCEPT_EULA: "Y"
    rabbit_mq:
        image: "rabbitmq:3-management"
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}