// <auto-generated />
using System;
using Mango.Services.CouponAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.CouponAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220124220538_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mango.Services.CouponAPI.Entities.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Coupons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "10OFF",
                            DiscountAmount = 10.0,
                            PublicId = new Guid("770a4868-d099-4b62-ab22-ff62ab4929c7")
                        },
                        new
                        {
                            Id = 2,
                            Code = "20OFF",
                            DiscountAmount = 20.0,
                            PublicId = new Guid("20315dc3-9772-4343-afb5-646d21ad7c78")
                        },
                        new
                        {
                            Id = 3,
                            Code = "30OFF",
                            DiscountAmount = 30.0,
                            PublicId = new Guid("1783df47-55b6-44b9-8f84-a4e64318308c")
                        },
                        new
                        {
                            Id = 4,
                            Code = "40OFF",
                            DiscountAmount = 40.0,
                            PublicId = new Guid("e70dd92d-8c28-4a1c-aeda-a3071d0df91d")
                        },
                        new
                        {
                            Id = 5,
                            Code = "50OFF",
                            DiscountAmount = 50.0,
                            PublicId = new Guid("92c9e9ec-99c8-453e-9435-303e33b98001")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
