// <auto-generated />
using System;
using Mango.Services.CouponAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.CouponAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mango.Services.CouponAPI.Entities.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Coupons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "10OFF",
                            DiscountAmount = 10.0,
                            PublicId = new Guid("21127ea1-7c7a-47df-b5e5-e83c45ca112b")
                        },
                        new
                        {
                            Id = 2,
                            Code = "20OFF",
                            DiscountAmount = 20.0,
                            PublicId = new Guid("6109c6ee-0193-4728-ae49-01a447d16831")
                        },
                        new
                        {
                            Id = 3,
                            Code = "30OFF",
                            DiscountAmount = 30.0,
                            PublicId = new Guid("42de469a-3842-4b6b-8f37-8f7d50213b48")
                        },
                        new
                        {
                            Id = 4,
                            Code = "40OFF",
                            DiscountAmount = 40.0,
                            PublicId = new Guid("bf84eec2-ec47-4468-b049-1c00b3f317d6")
                        },
                        new
                        {
                            Id = 5,
                            Code = "50OFF",
                            DiscountAmount = 50.0,
                            PublicId = new Guid("e53c63bd-a2a3-4e7a-b997-907fe0d66aa7")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
