// <auto-generated />
using System;
using Mango.Services.CouponAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.CouponAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mango.Services.CouponAPI.Entities.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Coupons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "10OFF",
                            DiscountAmount = 10.0,
                            PublicId = new Guid("d40064cf-2d4b-4afb-9883-c0f75841f54c")
                        },
                        new
                        {
                            Id = 2,
                            Code = "20OFF",
                            DiscountAmount = 20.0,
                            PublicId = new Guid("34efd893-9480-4e49-94f3-42a6a422342d")
                        },
                        new
                        {
                            Id = 3,
                            Code = "30OFF",
                            DiscountAmount = 30.0,
                            PublicId = new Guid("74caf3f9-a81a-493b-b158-621f1d580214")
                        },
                        new
                        {
                            Id = 4,
                            Code = "40OFF",
                            DiscountAmount = 40.0,
                            PublicId = new Guid("75869737-dd15-4910-853f-7b1b7c31398f")
                        },
                        new
                        {
                            Id = 5,
                            Code = "50OFF",
                            DiscountAmount = 50.0,
                            PublicId = new Guid("18b3e267-6868-4f7a-b1c6-e420255b8d12")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
